import { vi } from 'vitest'
import type { TrophyLockerApi } from '@shared/ipc'

export function fakeApi(overrides: Partial<TrophyLockerApi> = {}): TrophyLockerApi {
  return {
    getAppInfo: vi.fn().mockResolvedValue({ version: '0.1.0', schemaVersion: 1 }),
    sendTestNotification: vi.fn().mockResolvedValue(undefined),
    getProfile: vi.fn().mockResolvedValue({ name: null, windowsName: 'adam' }),
    setProfileName: vi.fn((name: string) =>
      Promise.resolve({ name: name.trim() === '' ? null : name.trim(), windowsName: 'adam' }),
    ),
    getNotificationsPaused: vi.fn().mockResolvedValue(false),
    setNotificationsPaused: vi.fn().mockResolvedValue(undefined),
    listAccounts: vi.fn().mockResolvedValue([]),
    disconnectAccount: vi.fn().mockResolvedValue(undefined),
    syncNow: vi.fn().mockResolvedValue(undefined),
    connectSteam: vi.fn(),
    connectXbox: vi.fn(),
    cancelXboxSignIn: vi.fn().mockResolvedValue(undefined),
    openEpicSignIn: vi.fn().mockResolvedValue(undefined),
    connectEpic: vi.fn(),
    connectUbisoft: vi.fn(),
    cancelUbisoftSignIn: vi.fn().mockResolvedValue(undefined),
    connectEa: vi.fn(),
    cancelEaSignIn: vi.fn().mockResolvedValue(undefined),
    connectPlayStation: vi.fn(),
    cancelPlayStationSignIn: vi.fn().mockResolvedValue(undefined),
    signInToSteam: vi.fn(),
    cancelSteamSignIn: vi.fn().mockResolvedValue(undefined),
    listLibrary: vi.fn().mockResolvedValue([]),
    getGame: vi.fn().mockResolvedValue(null),
    mergeGames: vi.fn().mockResolvedValue(undefined),
    unlinkGame: vi.fn().mockResolvedValue(undefined),
    getArtworkSettings: vi.fn().mockResolvedValue({ hasKey: false, missing: 0, problem: null }),
    saveSteamGridDbKey: vi.fn(),
    removeSteamGridDbKey: vi.fn().mockResolvedValue(undefined),
    findMissingArtwork: vi.fn().mockResolvedValue({ found: 0, checked: 0 }),
    getDashboard: vi.fn().mockReturnValue(new Promise(() => {})),
    listActivity: vi.fn().mockReturnValue(new Promise(() => {})),
    onDataChanged: vi.fn(() => () => {}),
    onToasts: vi.fn(() => () => {}),
    onNotificationsPausedChanged: vi.fn(() => () => {}),
    ...overrides,
  }
}
